package bg.tuvarna.sit.wms.entities.base;

import java.io.Serializable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a base entity class that provides common properties
 * for all entities in the system. This class serves as a foundation
 * for entity inheritance and ensures that all entities have a unique ID.
 * <p>
 * Entities inheriting from this class will inherit the ID property,
 * which is auto-generated and has a database identity strategy.
 * </p>
 *
 * @author Yavor Chamov
 * @version 1.0.0
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity implements Serializable {

  /**
   * Represents the unique identifier for each entity instance.
   * It's auto-generated by the database using an identity strategy.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
}
